// @workerv2/pdf-export — the PDF Export Processor. The first concrete document exporter, built with
// the Processor SDK, that converts an immutable Document into a DETERMINISTIC PDF Artifact:
//
//   Document → PDF Export Processor → PDF Generator → validated PDF → PDF Artifact (+ PDF Descriptor)
//
// It consumes immutable Documents and resolves referenced Page Artifacts; it modifies no Documents,
// renders no pages, processes no images (only packs decoded page samples into PDF image XObjects),
// composes no layouts, introduces no business logic, and performs no storage/networking — production
// goes through the Artifact Platform via the SDK gateway. The PDF is generated by a pure-TypeScript
// writer that overrides/normalizes every non-deterministic value (timestamps, random ids, object
// ordering, producer metadata), so identical inputs yield byte-identical PDFs. Future exporters
// (preview images, print packages, archival formats) follow this same architecture.

// --- Processor (Processor SDK) ---
export { pdfExportSpec, createPdfExportProcessor, SLOT } from './processor.js';

// --- Export configuration ---
export type {
  PdfVersion,
  PdfCompression,
  PdfExportMetadata,
  PdfExportConfig,
  ResolvedPdfConfig,
} from './config.js';
export {
  PDF_EXPORTER_VERSION,
  PDF_VERSIONS,
  PDF_COMPRESSIONS,
  DEFAULT_PDF_CONFIG,
  parsePdfExportConfig,
  canonicalExportConfig,
} from './config.js';

// --- PDF generator / assembly engine ---
export { generatePdf, PDF_PRODUCER } from './pdf-generator.js';
export type { GeneratorPage, PdfInfo } from './pdf-generator.js';
export { rasterToPdfImage } from './pdf-image.js';
export type { PdfImage, PdfColorSpace } from './pdf-image.js';

// --- Low-level PDF writer (deterministic) ---
export { PdfBuilder, pdfTextString, streamObject } from './pdf-writer.js';

// --- Validation ---
export { validateExportPages, validatePdf } from './validate.js';

// --- PDF descriptor ---
export { buildPdfDescriptor, PDF_DESCRIPTOR_SCHEMA } from './descriptor.js';
export type { PdfDescriptor } from './descriptor.js';

// --- Errors ---
export { PdfExportError } from './errors.js';

// --- Test harness (reusable) ---
export { setupPdfExport, samplePageRaster, samplePrintProfile } from './harness.js';
export type { PdfExportSetup, PdfExportSetupOptions } from './harness.js';
