import type { Result } from '@workerv2/contracts';
import { ok, err } from '@workerv2/utils';
import type { RasterImage } from '@workerv2/image-backend';

/**
 * EXPORT VALIDATION — two gates. `validateExportPages` checks the resolved page rasters are
 * consistent BEFORE generation (uniform dimensions — a document is a uniform-page album). `validatePdf`
 * checks the generated bytes are a well-formed PDF BEFORE the Artifact is produced. Together with the
 * document/config parsers upstream, they ensure an invalid PDF Artifact is never produced.
 */

/** Validate that resolved page rasters are internally consistent (same dimensions). */
export function validateExportPages(pages: readonly RasterImage[]): Result<void, string> {
  if (pages.length === 0) return err('document has no pages to export');
  const first = pages[0];
  if (first === undefined) return err('document has no pages to export');
  for (let i = 1; i < pages.length; i += 1) {
    const page = pages[i];
    if (page === undefined) continue;
    if (page.width !== first.width || page.height !== first.height) {
      return err(
        `inconsistent page sizes: page ${i} is ${page.width}x${page.height}, expected ${first.width}x${first.height}`,
      );
    }
  }
  return ok(undefined);
}

const PDF_HEADER = '%PDF-';
const EOF_MARKER = '%%EOF';

/** Structurally validate generated PDF bytes (header, catalog, xref/trailer, EOF). */
export function validatePdf(bytes: Uint8Array): Result<void, string> {
  if (bytes.length < 32) return err('generated PDF is too small');
  const head = latin1(bytes.subarray(0, 8));
  if (!head.startsWith(PDF_HEADER)) return err('generated PDF is missing the %PDF- header');

  // Check the tail for startxref + %%EOF (scan a bounded window from the end).
  const tail = latin1(bytes.subarray(Math.max(0, bytes.length - 256)));
  if (!tail.includes('startxref')) return err('generated PDF is missing startxref');
  if (!tail.trimEnd().endsWith(EOF_MARKER)) return err('generated PDF is missing the %%EOF marker');

  const body = latin1(bytes);
  if (!body.includes('/Type /Catalog')) return err('generated PDF is missing the catalog');
  if (!body.includes('xref')) return err('generated PDF is missing the cross-reference table');
  if (!body.includes('/Type /Page')) return err('generated PDF has no page objects');
  return ok(undefined);
}

function latin1(bytes: Uint8Array): string {
  let out = '';
  for (let i = 0; i < bytes.length; i += 1) out += String.fromCharCode(bytes[i] as number);
  return out;
}
