'use client';

import { useRef, useState } from 'react';
import { InlineLoader } from '@/components/loading';
import { useRouter } from 'next/navigation';
import { Upload, Trash2, Eye, EyeOff, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { presignCoverUpload, createCover, setCoverActive, deleteCover } from '@/lib/actions/admin/covers';
import { useWorkerGate } from '@/components/worker/use-worker-gate';
import type { AdminCover } from '@/lib/admin/covers';

const ACCEPT = 'image/jpeg,image/png,image/webp';
const fmtDate = (s: string) => new Date(s).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });

export default function CoversManager({ covers }: { covers: AdminCover[] }) {
  const router = useRouter();
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [toDelete, setToDelete] = useState<AdminCover | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const { ensureReady, modal: workerModal } = useWorkerGate();

  const upload = async () => {
    setError(null);
    if (!name.trim()) return setError('Give the cover a name.');
    if (!file) return setError('Choose an image file.');
    // The cover thumbnail is generated by the worker — wake it before registering.
    if (!(await ensureReady())) return;
    setBusy(true);
    try {
      const pre = await presignCoverUpload({ filename: file.name, contentType: file.type, size: file.size });
      if (!pre.ok) return setError(pre.error);
      const put = await fetch(pre.uploadUrl, { method: 'PUT', headers: { 'Content-Type': file.type }, body: file });
      if (!put.ok) return setError('Upload to storage failed.');
      const res = await createCover({
        name: name.trim(),
        description: description.trim() || undefined,
        imageKey: pre.key,
        sort: covers.length,
      });
      if (!res.ok) return setError(res.error);
      setName('');
      setDescription('');
      setFile(null);
      if (fileRef.current) fileRef.current.value = '';
      router.refresh();
    } finally {
      setBusy(false);
    }
  };

  const toggle = async (c: AdminCover) => {
    await setCoverActive({ coverTemplateId: c.id, active: !c.active });
    router.refresh();
  };

  const confirmDelete = async () => {
    if (!toDelete) return;
    setBusy(true);
    const res = await deleteCover({ coverTemplateId: toDelete.id });
    setBusy(false);
    setToDelete(null);
    if (!res.ok) setError(res.error);
    router.refresh();
  };

  return (
    <div className="space-y-6">
      {/* Upload */}
      <section className="rounded-lg border bg-card p-4">
        <h2 className="text-sm font-semibold">Add a cover design</h2>
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          <div>
            <label className="mb-1 block text-xs text-muted-foreground">Name</label>
            <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Classic Linen" maxLength={100} />
          </div>
          <div>
            <label className="mb-1 block text-xs text-muted-foreground">Description (optional)</label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Short note" maxLength={300} />
          </div>
        </div>
        <div className="mt-3 flex flex-wrap items-end gap-3">
          <div>
            <label className="mb-1 block text-xs text-muted-foreground">Artwork (JPEG/PNG/WebP)</label>
            <input ref={fileRef} type="file" accept={ACCEPT} onChange={(e) => setFile(e.target.files?.[0] ?? null)} className="text-sm" />
          </div>
          <Button size="sm" onClick={upload} disabled={busy}>
            {busy ? <InlineLoader /> : <Upload />} Upload
          </Button>
        </div>
        <p className="mt-2 text-xs text-muted-foreground">
          Use a print-ready portrait image (3:4, ideally {1800}×{2400}px / 300 DPI). It becomes physical page 1; users select it
          but cannot edit it.
        </p>
        {error && <p className="mt-2 text-sm text-destructive">{error}</p>}
      </section>

      {/* Catalogue */}
      {covers.length === 0 ? (
        <p className="text-sm text-muted-foreground">No cover designs yet. Upload one above.</p>
      ) : (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
          {covers.map((c) => (
            <div key={c.id} className={`overflow-hidden rounded-lg border bg-card ${c.active ? '' : 'opacity-60'}`}>
              <div className="relative aspect-[3/4] w-full bg-muted">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={c.thumbUrl} alt={c.name} className="absolute inset-0 h-full w-full object-cover" />
                {!c.active && (
                  <span className="absolute left-1 top-1 rounded bg-background/85 px-1.5 py-0.5 text-[10px] font-medium">Hidden</span>
                )}
                {c.lowRes && (
                  <span className="absolute right-1 top-1 inline-flex items-center gap-0.5 rounded bg-amber-500/90 px-1.5 py-0.5 text-[10px] font-medium text-white">
                    <AlertTriangle className="h-3 w-3" /> Low-res
                  </span>
                )}
              </div>
              <div className="space-y-1 p-2">
                <div className="flex items-center justify-between gap-1">
                  <span className="truncate text-xs font-medium" title={c.name}>
                    {c.name}
                  </span>
                  <div className="flex shrink-0 items-center">
                    <Button variant="ghost" size="icon-sm" onClick={() => toggle(c)} aria-label={c.active ? 'Hide' : 'Show'}>
                      {c.active ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}
                    </Button>
                    <Button variant="ghost" size="icon-sm" onClick={() => setToDelete(c)} aria-label="Delete" className="text-destructive">
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                {c.description && <p className="truncate text-[11px] text-muted-foreground" title={c.description}>{c.description}</p>}
                <p className="text-[11px] text-muted-foreground">
                  {c.width && c.height ? `${c.width}×${c.height}` : 'measuring…'} · {fmtDate(c.createdAt)}
                  {c.usedBy > 0 ? ` · used by ${c.usedBy}` : ''}
                </p>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Delete confirmation (Part 4) */}
      {toDelete && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={() => setToDelete(null)}>
          <div className="w-full max-w-sm rounded-xl border bg-background p-5 shadow-lg" onClick={(e) => e.stopPropagation()}>
            <h2 className="text-base font-semibold">Delete “{toDelete.name}”?</h2>
            <p className="mt-2 text-sm text-muted-foreground">Are you sure you want to delete this cover template?</p>
            <p className="mt-2 text-sm text-muted-foreground">
              {toDelete.usedBy > 0
                ? `This cover is used by ${toDelete.usedBy} album${toDelete.usedBy === 1 ? '' : 's'}. It will be deactivated (not erased) — existing albums and purchased PDFs keep working, but new albums cannot select it.`
                : 'This cover is not used by any album, so it will be permanently deleted along with its artwork.'}
            </p>
            <div className="mt-4 flex justify-end gap-2">
              <Button variant="ghost" size="sm" onClick={() => setToDelete(null)} disabled={busy}>
                Cancel
              </Button>
              <Button variant="destructive" size="sm" onClick={confirmDelete} disabled={busy}>
                {busy ? <InlineLoader /> : <Trash2 />}{' '}
                {toDelete.usedBy > 0 ? 'Deactivate' : 'Delete'}
              </Button>
            </div>
          </div>
        </div>
      )}

      {workerModal}
    </div>
  );
}
